export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const SAVE_TRANSACTION ='SAVE_TRANSACTION';
export const FETCH_TRANSACTIONS ='FETCH_TRANSACTIONS';
export const FETCH_TRANSACTIONS_SUCCESS ='FETCH_TRANSACTIONS_SUCCESS';
export const DELETE_TRANSACTION ='DELETE_TRANSACTION';
export const UPDATE_TRANSACTION ='UPDATE_TRANSACTION';
export const SAVE_TRANSACTION_SUCCESS = 'SAVE_TRANSACTION_SUCCESS'
export const FETCH_CATEGORY_SUCCESS ='FETCH_CATEGORY_SUCCESS';

